package natural

// Return the serie of triangle numbers, generated by adding the natural numbers
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
func Triangle(max int) chan int64 {

	ch := make(chan int64)
	go func() {
		defer close(ch)
		total := int64(0)
		for i := 1; i <= max; i++ {
			total += int64(i)
			ch <- total
		}
	}()
	return ch
}
